package br.com.musicianapp.impl;

public enum ConsultasPadrao {
	TELEFONE_TUDO,TELEFONE_ID,
	ITEM_PRODUTO_TRADE,
	PEDIDO_ID,PEDIDO_TUDO,PEDIDO_POR_USUARIO,
	PESSOA_ID,PESSOA_NOME,PESSOA_CPF,PESSOA_TUDO,
	PRODUTO_ID, PRODUTO_TUDO,
	USUARIO_ID, USUARIO_TUDO, USUARIO_HASH, USUARIO_LOGIN,
	CARTAO_ID, CARTAO_TUDO,
	CUPOM_ID, CUPOM_TUDO,
	ENDERECO_ID, ENDERECO_TUDO
}
